#!/usr/bin/env sh

CHARGING_ICON="⚡"     #  U+26A1 -  Thunderbolt
DISCHARGING_ICON="🔋" # U+1F50B - Battery

print_help() {
    echo "usage: battstat [options] format"
    echo ""
    echo "options:"
    echo "    -h, --help                display help information"
    echo "    --percent-when-charged    only display percent when charged"
    echo ""
    echo "format:"
    echo "    {i}    display icon"
    echo "    {t}    display time remaining"
    echo "    {p}    display percent"
    echo ""
    echo "    Note: There must be a space between each format token."

}

get_darwin_vars() {
    # Exit if no battery exists.
    if [ -z "$(pmset -g batt | grep 'InternalBattery')" ]; then
	echo "No battery found."
	exit 1
    fi

    CHARGED=$(pmset -g batt | grep -w "charged")
    CHARGING=$(pmset -g batt | grep -w "AC Power")
    DISCHARGING=$(pmset -g batt | grep -w "Battery Power")
    TIME=$(pmset -g batt | grep InternalBattery | awk '{print $5}' | grep '^[0-9]')
    PERCENT=$(pmset -g batt | grep InternalBattery | awk '{print $3}')
    PERCENT=${PERCENT%?} # Strips the last character (;)
}

get_linux_vars() {
    # Exit if no batery exists.
    BATTERY_SYSFS_PATH="/sys/class/power_supply/BAT0"
    if [ ! -d "$BATTERY_SYSFS_PATH" ]; then
	echo "No battery found."
	exit 1
    fi

    CHARGED=$(cat $BATTERY_SYSFS_PATH/status | grep -w "Full")
    CHARGING=$(cat $BATTERY_SYSFS_PATH/status | grep -w "Charging")
    DISCHARGING=$(cat $BATTERY_SYSFS_PATH/status | grep -w "Discharging")
    TIME=""
    PERCENT=$(cat $BATTERY_SYSFS_PATH/capacity)
    PERCENT="$PERCENT%"
}

hide_percent_until_charged() {
    if [ -z "$CHARGED" ]; then
	PERCENT=""
    fi
}   

print_icon() {
    if [ ! -z "$CHARGING" ] || [ ! -z $CHARGED ]; then
	ICON=$CHARGING_ICON
    elif [ ! -z "$DISCHARGING" ]; then
	ICON=$DISCHARGING_ICON
    fi

    printf " %s " $ICON
}

print_time() {
    # Display "calc..." when calculating time remaining.
    if [ -z "$TIME" ] || [ $TIME = "0:00" ]; then
	TIME="calc..."
    fi

    # Hide time when fully charged.
    if [ ! -z "$CHARGED" ]; then
	TIME=""
    fi
    
    if [ ! -z "$TIME" ]; then
	printf " %s " $TIME
    fi

}

print_percent() {
    if [ ! -z "$PERCENT" ]; then
	printf " %s " $PERCENT
    fi
}

case $(uname) in
    "Darwin")
	get_darwin_vars
	;;
    "Linux")
	echo "Linux is currently not supported."
	exit 1
	get_linux_vars
	;;
esac

if [ $# -eq 0 ]; then
    print_help
fi

while test $# -gt 0; do
    case "$1" in
	-h|--help)
	    print_help
	    break
	    ;;
	--percent-when-charged)
	    hide_percent_until_charged
	    shift
	    ;;
	{i})
	    print_icon
	    shift
	    ;;
	{t})
	    print_time
	    shift
	    ;;
	{p})
	    print_percent
	    shift
	    ;;
	*)
	    print_help
	    break
	    ;;
    esac
done

printf "\n"
